### ISSUE TITLE
关于iOSdemo编译，是否需要开发和账号或者付费账号？

### ISSUE THREAD

**Issue by xuandu** [HackWebRTC/webrtc#16]
个人没付费的账号可以用吗？网上有人说账号必须是付费的或者企业管理员权限的？我自己编译在只改了info.plist的情况下，编译不过
note: Compile and copy AppRTCMobile via ninja
ninja: Entering directory `.'
[1/38] STAMP obj/sdk/ios_framework_bundle.stamp
[2/38] STAMP obj/examples/apprtc_signaling.inputdeps.stamp
[3/38] STAMP obj/examples/AppRTCMobile_lib.inputdeps.stamp
[4/38] STAMP obj/examples/AppRTCMobile_arch_executable_sources.stamp
[5/38] ACTION //examples:AppRTCMobile_generate_info_plist(//build/toolchain/mac:ios_clang_arm64)
FAILED: gen/examples/AppRTCMobile_generate_info_plist.plist 
python ../../build/config/mac/plist_util.py substitute -f=binary1 -o=gen/examples/AppRTCMobile_generate_info_plist.plist -t=gen/examples/AppRTCMobile_generate_info_plist_merged.plist -s=BUILD_MACHINE_OS_BUILD=19D76 -s=EXECUTABLE_NAME=AppRTCMobile -s=GCC_VERSION=com.apple.compilers.llvm.clang.1_0 -s=PRODUCT_NAME=AppRTCMobile -s=XCODE_BUILD=11C504 -s=XCODE_VERSION=1131 -s=IOS_DEPLOYMENT_TARGET=10.0 -s=IOS_BUNDLE_ID_PREFIX=org.chromium -s=IOS_PLATFORM_BUILD=17B102 -s=IOS_PLATFORM_NAME=iphoneos -s=IOS_PLATFORM_VERSION=13.2 -s=IOS_SDK_BUILD=17B102 -s=IOS_SDK_NAME=iphoneos13.2 -s=IOS_SUPPORTED_PLATFORM=iPhoneOS
Traceback (most recent call last):
  File "../../build/config/mac/plist_util.py", line 226, in <module>
    sys.exit(Main())
  File "../../build/config/mac/plist_util.py", line 222, in Main
    args.func(args)
  File "../../build/config/mac/plist_util.py", line 210, in _Execute
    data = Interpolate(LoadPList(args.template), substitutions)
  File "../../build/config/mac/plist_util.py", line 82, in Interpolate
    return {k: Interpolate(v, substitutions) for k, v in value.iteritems()}
  File "../../build/config/mac/plist_util.py", line 82, in <dictcomp>
    return {k: Interpolate(v, substitutions) for k, v in value.iteritems()}
  File "../../build/config/mac/plist_util.py", line 86, in Interpolate
    return InterpolateString(value, substitutions)
  File "../../build/config/mac/plist_util.py", line 65, in InterpolateString
    value = substitution_regexp.sub(repl, value)
  File "../../build/config/mac/plist_util.py", line 52, in repl
    raise SubstitutionError(variable)
__main__.SubstitutionError: SubstitutionError: MARKETING_VERSION
[6/38] LINK obj/examples/arm64/AppRTCMobile
ninja: build stopped: subcommand failed.
Command PhaseScriptExecution failed with a nonzero exit code

我编译的iOS，可是也不清楚他为什么会访问Mac的文件。

**Comment by Piasy** [comment]
应该是不需要的，个人账号也可以真机调试。

官方 demo 的详细运行步骤，以及编译环境搭建，可以看我的新书：《WebRTC Native 开发实战》，清华大学出版社，作者许建林。天猫、京东、当当等电商平台均可搜索到。
