### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by CoderZYLiao** [HackWebRTC/webrtc#56]
gn gen out/xcode_ios_arm64 --args='target_os="ios" target_cpu="arm64"' --ide=xcode 
ERROR at //build/config/mac/mac_sdk.gni:85:5: Script returned non-zero exit code.
    exec_script("//build/mac/find_sdk.py", find_sdk_args, "list lines")
    ^----------
Current dir: /Users/leo/webrtc_test/src/out/xcode_ios_arm64/
Command: python /Users/leo/webrtc_test/src/build/mac/find_sdk.py --print_sdk_path --print_bin_path 10.12
Returned 1.
stderr:

Traceback (most recent call last):
  File "/Users/leo/webrtc_test/src/build/mac/find_sdk.py", line 127, in <module>
    print(main())
  File "/Users/leo/webrtc_test/src/build/mac/find_sdk.py", line 96, in main
    raise Exception('No %s+ SDK found' % min_sdk_version)
Exception: No 10.12+ SDK found

See //build/toolchain/mac/BUILD.gn:15:1: whence it was imported.
import("//build/config/mac/mac_sdk.gni")
^--------------------------------------
See //BUILD.gn:29:3: which caused the file to be included.
  group("default") {
  ^-----------------

**Comment by CoderZYLiao** [comment]
> gn gen out/xcode_ios_arm64 --args='target_os="ios" target_cpu="arm64"' --ide=xcode ERROR at //build/config/mac/mac_sdk.gni:85:5: 脚本返回非零退出代码。 exec_script("//build/mac/find_sdk.py", find_sdk_args, "list lines") ^------- 当前目录：/Users/leo/webrtc_test/src/out/xcode_ios_arm64/ 命令：python /Users/leo/webrtc_test/src/build/mac/find_sdk.py --print_sdk_path --print_bin_path 10.12 返回 1. stderr：
> 
> 回溯（最近一次调用最后一次）： 文件“/Users/leo/webrtc_test/src/build/mac/find_sdk.py”，第 127 行，在 print(main())中 文件“/Users/leo/webrtc_test/src/build/mac/find_sdk.py”，第 96 行，在 main 中 引发异常（'未找到 %s+ SDK' % min_sdk_version） 异常：未找到 10.12+ SDK
> 
> 请参阅 //build/toolchain/mac/BUILD.gn:15:1: 导入的位置。 import("//build/config/mac/mac_sdk.gni") ^-------------------------------------- 请参阅 //BUILD.gn:29:3: 导致文件被包含。 group("default") { ^-----------------

使用这个命令列出自己当前的sdk版本
xcodebuild -showsdks

找到第75行
例如我的sdk版本是13.2，所以我改成了13
修改:
75行: sdks = [re.findall(MacOSX(13\id+).sdk$', s) for s in os.listdir(sdk dir)
